In [28]:
import numpy as np
import os
from PIL import Image
import matplotlib.pylab as plb

In [29]:
for item in os.listdir(r'C:\Users\Waqar Ahmed\Desktop\Images'):
    image1=Image.open('C:\\Users\Waqar Ahmed\\Desktop\\Images\\'+item)
    image1.thumbnail((200,200))
    image1.save('C:\\Users\\Waqar Ahmed\\Desktop\\imagesned\\'+item)
    image2=plb.imread('C:\\Users\\Waqar Ahmed\\Desktop\\imagesned\\'+item)
    print(image2)

[[[0.09019608 0.18431373 0.41960785]
  [0.09019608 0.18431373 0.41960785]
  [0.09019608 0.18431373 0.41960785]
  ...
  [0.31764707 0.5058824  0.7490196 ]
  [0.32941177 0.5176471  0.7607843 ]
  [0.3372549  0.5254902  0.76862746]]

 [[0.09019608 0.18431373 0.41960785]
  [0.09019608 0.18431373 0.41960785]
  [0.09019608 0.18431373 0.41960785]
  ...
  [0.32941177 0.5176471  0.7607843 ]
  [0.34117648 0.5294118  0.77254903]
  [0.34901962 0.5372549  0.78039217]]

 [[0.08627451 0.18039216 0.41568628]
  [0.08627451 0.18039216 0.41568628]
  [0.08627451 0.18039216 0.41568628]
  ...
  [0.3254902  0.5137255  0.75686276]
  [0.33333334 0.52156866 0.7647059 ]
  [0.34117648 0.5294118  0.77254903]]

 ...

 [[0.41960785 0.6156863  0.16862746]
  [0.5137255  0.7058824  0.25490198]
  [0.34901962 0.5411765  0.10196079]
  ...
  [0.20784314 0.34509805 0.10980392]
  [0.23137255 0.39215687 0.05098039]
  [0.49803922 0.67058825 0.22745098]]

 [[0.40392157 0.59607846 0.16078432]
  [0.4627451  0.6509804  0.21568628]


  [0.83137256 0.23137255 0.29803923]]]
[[[0.7607843  0.98039216 0.14509805]
  [0.77254903 0.972549   0.17254902]
  [0.8117647  0.96862745 0.24705882]
  ...
  [0.69803923 0.9882353  0.14901961]
  [0.7882353  0.99607843 0.2       ]
  [0.8627451  0.9882353  0.23921569]]

 [[0.7529412  0.972549   0.16470589]
  [0.76862746 0.96862745 0.19215687]
  [0.80784315 0.9647059  0.25882354]
  ...
  [0.6509804  0.96862745 0.12156863]
  [0.7490196  0.99215686 0.18039216]
  [0.8352941  0.9882353  0.22352941]]

 [[0.74509805 0.972549   0.19607843]
  [0.75686276 0.9647059  0.21960784]
  [0.79607844 0.9647059  0.27450982]
  ...
  [0.5529412  0.93333334 0.0627451 ]
  [0.6666667  0.96862745 0.13333334]
  [0.76862746 0.9764706  0.18431373]]

 ...

 [[0.08235294 0.1764706  0.09019608]
  [0.0627451  0.15686275 0.07058824]
  [0.03529412 0.12941177 0.04313726]
  ...
  [0.3647059  0.2784314  0.09411765]
  [0.36078432 0.23137255 0.05882353]
  [0.36862746 0.2        0.04313726]]

 [[0.08627451 0.18039216 0.09411765

[[[0.5882353  0.6666667  1.        ]
  [0.5882353  0.6666667  1.        ]
  [0.5882353  0.6666667  1.        ]
  ...
  [0.78039217 0.9647059  0.7647059 ]
  [0.7764706  0.96862745 0.7529412 ]
  [0.7529412  0.9764706  0.7764706 ]]

 [[0.5882353  0.6666667  1.        ]
  [0.5882353  0.6666667  1.        ]
  [0.5882353  0.6666667  1.        ]
  ...
  [0.78431374 0.9607843  0.7647059 ]
  [0.78039217 0.9647059  0.7607843 ]
  [0.75686276 0.972549   0.78039217]]

 [[0.5882353  0.6666667  1.        ]
  [0.5882353  0.6666667  1.        ]
  [0.5882353  0.6666667  1.        ]
  ...
  [0.79607844 0.95686275 0.78039217]
  [0.7921569  0.9607843  0.77254903]
  [0.76862746 0.972549   0.78431374]]

 ...

 [[0.58431375 0.99607843 0.8666667 ]
  [0.58431375 1.         0.85490197]
  [0.5803922  0.99607843 0.84313726]
  ...
  [0.16862746 0.36078432 0.03529412]
  [0.20784314 0.4117647  0.        ]
  [0.21176471 0.43137255 0.01176471]]

 [[0.58431375 0.99607843 0.8666667 ]
  [0.58431375 1.         0.85882354]
